// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/chenwm-topstar/chargingc/pbs/commonpb/types.proto

package commonpb

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *EvseModel) Validate() error {
	return nil
}
func (this *EvseConfigKV) Validate() error {
	return nil
}
